### ISSUE TITLE
subjective project assessment tag similar to geek code

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#14]
[Geek Code](https://en.wikipedia.org/wiki/Geek_Code) was a column of letters & symbols to give a brief description of one self to other geeks that know how to interpret this code.

EXAMPLE:\
-----BEGIN GEEK CODE BLOCK-----
  Version: 3.1
  GED/J d-- s:++>: a-- C++(++++) ULU++ P+ L++ E---- W+(-) N+++ o+ K+++ w---
  O- M+ V-- PS++>$ PE++>$ Y++ PGP++ t- 5+++ X++ R+++>$ tv+ b+ DI+++ D+++
  G+++++ e++ h r-- y++**
------END GEEK CODE BLOCK------

Where e.g. `s` is the `size` property:

```
s+++ I take up three movie seats.
s++  I'm a linebacker candidate.
s+   I'm a little rounder than most.
s    I'm an average geek.
s-   Everybody tells me to gain a few pounds.
s--  I tend to have to fight against a strong breeze.
s--- My bones are poking through my skin.
```

[This talk](https://media.ccc.de/v/36c3-10608-das_nutzlich-unbedenklich_spektrum) (german) mentions the usefulness when adopted to software modules.

A property `I` (Intent, Confidence) was introduced like that:

```
I+++ I make actual guarantees.
I++  I have done this multiple times before. I know what I'm doing.
I+   I had to adopt the design a bit over time.
I    I tried to avoid security bugs while writing this.
I-   Look, they paid me to do this.
I--  The guy left. Code now maintained by team in India.
!I I have no idea what I'm doing.
```

I felt this comes close to a decentralised Open-O-Meter approach and could be applied to hardware modules. Especially the level of profession that flew into a machine or how well/active it is maintained are factors generally hard to assess when just looking on the source files. Also judging from commit frequencies etc. can be misleading. When was the last update/commit for the hexagon screw?

And yes, we may want to choose a less geeky way to communicate these properties :)

**Comment by moedn** [comment]
suggestion for fields to self assess then:

### target group

t+  hardcore specialists
t  casual engineers
t-  regular dude
t-- regular kid

### maintenance



### confidence

c+++ I make actual guarantees.
c++  I have done this multiple times before. I know what I'm doing.
c+   I had to adopt the design a bit over time.
c    I tried to avoid security bugs while writing this.
c-   Look, they paid me to do this.
c--  The guy left. Code now maintained by team in India.
!c I have no idea what I'm doing.

**Comment by hoijui** [comment]
das koennte man auch direkt in die projekt meta-daten rein machen, und zwar direkt verstaendlich
(ohne dass man ne legende braucht).

in *okh.yml* so in etwa (mit 0=0% und 10=100%):

```yaml
self-evaluation:
  code-quality: 6
  openness: 8
  developer-experience: 4
  issue-responsiveness: 3
```

... aber da sieht man dann auch schon,
das einige dieser daten genauer und vor allem aktueller waehren,
wenn man die generieren wuerde;
z.B. per abfragen und evaluieren alles issues per GihHub API.

ich glaub aber nicht,
dass wenn da ein super-coder rein schreibt,
dass er super viel erfahrung hat auf dem gebiet,
und spaeter uebernimt das projekt wer anderes mit wenig erfahrung,
dass diese person dann diesen wert in den meta-daten anpasst.
somit wuerden wir _stale data_ kriegen,
die mehr fehl-leitet als informiert.

**Comment by moedn** [comment]
Compared this idea with interviews & feedback we had in the last months. People are interested in confidence/project state first and foremost and it's yet very hard to get reliable data about that just from the repository.

I also want to avoid unnecessary additional data fields. So for me this boils down to one new field, called 

#### confidence/testing/intended use (or anything like that)

5 in decentralised mass-production (e.g. valid CE-certification) (e.g. Arduino)
4 in prototype production; stable & tested design, has been replicated many times without any involvement form our side; use at your own risk! (e.g. MNT Reform)
3 decentralised prototyping; other enthusiasts built and tested this (e.g. COSI Measure)
2 prototyping stage, I built _and_ tested this
1 development stage, no one has actually built this yet
0 idea stage

other things like openness, maintenance/activity can be assessed from other data (contribution guide, number of maintainers & contributors, commit history vs. issue history etc.)

---

A very interesting question is also the funding model behind a project e.g.

funded by public money
venture capital
donations/crowdfunding
100 % free time project

…so what's behind this. It often explains the dynamic of a project. But this is way too early to implement it as a new data field.

**Comment by moedn** [comment]
very interesting, but too much for this project and with high risk not to be maintained in manifest files. However, will consider this in future projects :)
