### ISSUE TITLE
new structure for project list

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#26]
(also in regard to #24)

As `project list` is growing we may want to restructure it

I propose the IPC system (International Patent Classification)
- relatively stable & internationally recognised
- applicable for all kinds of hardware
- data field in the requested metadata that certainly no one will provide 'out of stock', so people may be happy if we make a proposition.

_Originally posted by @moedn in https://github.com/OPEN-NEXT/OSHI/pull/23#discussion_r493470331_

**Comment by penyuan** [comment]
Sounds OK to me.

This might be naive, but maybe using the IPC has an additional benefit of slightly increasing awareness that open source hardware is compatible with commercial interests who traditionally think in a patent-only mindset...

**Comment by moedn** [comment]
Jepp, fully agree :)

It also facilitates patent research, so which open alternatives exist to proprietary hardware or whether it may infringe existing patents (super important question for enterprises)

**Comment by moedn** [comment]
moved to [LOSH-list](https://github.com/OPEN-NEXT/LOSH-list/)
