### ISSUE TITLE
translate JSON → JSON-LD

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#29]
Since we are asked to provide data in JSON-LD for the API, but JSON-LD is a lot less intuitive to write/use, we may want to include auto-conversion in the parser

**Comment by penyuan** [comment]
FYI, I found one implementation of the JSON-LD standard in Python 3.6+. It is [pyld](https://github.com/digitalbazaar/pyld) which last had a release in August 2020. Would it be helpful??? (I don't know the technicalities well enough to judge the usefulness of this library...)

**Comment by moedn** [comment]
Thanks! In our case the translation seems pretty straight-forward to me and mainly bases on our ontology.
