### ISSUE TITLE
[squashed] requests for new data fields & queries

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#31]
### data fields

- [x] organisation
  - to enable search for OSH developed under the umbrella of selected organisation (such as 'University of Bath', 'Open Source Ecolgy' etc.)
- [x] **operation environment envisioned** (free text, as required from TLR4)
- [x] number of contributors
- [x] timestamp (of commit of a specific file)
- software/firmware references
  - [x] link to release
  - [x] installation guide
- [x] user-manual
- [x] attestation
  - URL to OSHWA certificate or attestation according to DIN SPEC 3105-2

further ideas:

- design library
  - like UniProKit (UPKlib) or OSH standard furniture parts
  - …however, yet pretty uncommon (verify by T2.3)
  - sort of unofficial design standards in OSH
  - apparently OttoDIY uses this concept
  - with corresponding query to explore those

**Comment by moedn** [comment]
[Max/WIF] provide project stage based on stage assessment on a part base (not a mosh base)

**Comment by moedn** [comment]
it's yet unclear how design libraries work or are being used; until this is clear, I'll stage it as an idea

**Comment by hoijui** [comment]
`source` and `export` should probably be called `sources` and `exports`, to indicate that there can be multiple.
They also have to be explained better in the template, defining what should be in there and what not.
And most importantly, we have to do-away with manually specifying them! This makes the meta-data file creating and maintenance a lot more work, annoying and faulty.
