### ISSUE TITLE
Allow custom data fields?

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#34]
[OKHv1](https://app.standardsrepo.com/MakerNetAlliance/OpenKnowHow/src/branch/master/1) allows custom data fields in manifest files. And apparently people use them (not frequently, but still).

A few thoughts on this:

- custom input can serve as an experimental field; people can define fields themselves and query them without changing the ontology
- frequently used custom fields can be included in later updates of the ontology
- not sure how to integrate that in the ontology… ← any ideas? @hoijui

**Comment by hoijui** [comment]
do they have to appear in the ontology at all?
I can't think of a reason why they should.

If we parse them and put them as a kind of blob/catch all object in our DB, then.. how would we make use of it?

I would just ignore them. At some point, we might decide that one or the other of those fields make sense, and include them in a new version of the OKH standard, and then parse that field, to store it in the DB.

**Comment by hoijui** [comment]
... so the question is then, whether we

* issue an error if a non-standard field is detected
* a warning
* or whether we ignore it completely.

I would advocate for one of the later two.

**Comment by moedn** [comment]
Alright, as just agreed orally ↓

- people can put their additional information in the repository (e.g. readme) if they like
- we'll just ignore custom fields
- if people wish to have a new data field, they can file an issue and we update the ontology accordingly
