### ISSUE TITLE
[osh-metadata.ttl wikibase review] okh:name rdfs:subPropertyOf rdfs:label

### ISSUE THREAD

**Issue by addshore** [OPEN-NEXT/LOSH#36]
If `okh:name` is represented by a Statement in Wikibase, then this is not going to end up being a `rdfs:subPropertyOf rdfs:label`.
`rdfs:label` is only used by Wikibase Labels.

https://github.com/OPEN-NEXT/LOSH/blob/master/osh-metadata.ttl#L158

**Comment by hoijui** [comment]
@addshore Is it now ok? (see commits linked to above)

**Comment by addshore** [comment]
Generally looks good, per my comment in https://github.com/OPEN-NEXT/LOSH/issues/38#issuecomment-738807464 you may want to end up having both a single english label and to represent this as a statement (especially if you want to get into the realms of being able to reference where this data came from? but you may not want to do that?)

**Comment by moedn** [comment]
seems to be resolved then; however discussion about the extra statement continues in #38
