### ISSUE TITLE
[osh-metadata.ttl wikibase review] "reference" duplications

### ISSUE THREAD

**Issue by addshore** [OPEN-NEXT/LOSH#37]
There seems to be lots of duplication around the "reference" concept in the described ontology and I don't see the value here.
Within the ontology each entity is already going to have a "class" as described in the ontology, so if these references are intended for use alongside these classes I don't think this duplication is needed.
But perhaps I am missing sometihng?

  - Component Reference
   - Module Reference
   - Piece Reference
   - Standard Reference
   - Buy Reference

https://github.com/OPEN-NEXT/LOSH/blob/master/osh-metadata.ttl#L98-L114
https://github.com/OPEN-NEXT/LOSH/blob/master/osh-metadata.ttl#L128-L138

**Comment by moedn** [comment]
Great point, also caused a lot of discussion over here and yes, we agree :) pointless duplications.

Only `componentReference` will remain and get various ranges. Possible input restrictions (e.g. standard resignation for standard components) should happen on a higher level.

**Comment by hoijui** [comment]
done (see a14ca114b1a100d536a0629926bb1134742aa059)

**Comment by moedn** [comment]
Since only one range / datatype is possible, we need to role back to the original approach, but with more consistent wording to avoid confusion :)

so we have

- `ComponentReference` for 
  - MOSH
    - internal reference: URI to MOSH (added by the crawler from sBoM entry)
    - external reference: `ReleaseReference` (URL to specific MOSH version; from sBoM entry)
  - POSH
    - internal reference: URI to POSH (added by the crawler from sBoM entry)
  - STD
    - `StandardDesignation`
  - BUY
    - `FreeDesignation`

**Comment by moedn** [comment]
should be resolved now (again :) )
