### ISSUE TITLE
[osh-metadata.ttl wikibase review] okh:name could just be a Wikibase Label (and Aliases?)

### ISSUE THREAD

**Issue by addshore** [OPEN-NEXT/LOSH#38]
https://github.com/OPEN-NEXT/LOSH/blob/master/osh-metadata.ttl#L154-L161

Right now this is modeled as a Statement (hinted at by the `rdfs:subPropertyOf wdp:P2561 ;`) as also noted in #36 as the `rdfs:label` bit doesn't really make sense here.
This is totally possible, and may make sense, however it would also be possible to just use Wikibase Labels for this (if there is only one name), and aliases if there can be multiple names.

One of the main benefits here is being able to easily make use of the multi language support for Labels, and thus have this tie into the rest of Wikibase in a multi lingual way. (If you only represent this in statements you' won't get that).

However, if there is a canonical name in a set language that should be recorded, a statement would be good for this, but I don't feel that this is currently well represented in the ontology file.

**Comment by moedn** [comment]
Cool suggestion!
Thought a while about it, you're right. Even though 
- the vast majority of projects are documented in one language only anyway
- and use a canonical name in different language versions (if any)
- and we though that `okh:name` can be helpful for identification reasons etc. but other properties (such as `repo`) are much suitable for this

**Comment by moedn** [comment]
How multi-language support will look like in practice is still an open issue. This depends on the data that we'll get in the end. For the moment we're considering only documentation in English

**Comment by addshore** [comment]
> only documentation in English

Sounds fine.

So in Wikibase you will likely want to put the name as a english label and also create a property similar to https://www.wikidata.org/wiki/Property:P2561, which uses the `Monolingual text` data type

**Comment by moedn** [comment]
@addshore 

> So in Wikibase you will likely want to put the name as a english label and also create a property similar to https://www.wikidata.org/wiki/Property:P2561, which uses the `Monolingual text` data type

> […] (especially if you want to get into the realms of being able to reference where this data came from? but you may not want to do that?)

(from your [comment](https://github.com/OPEN-NEXT/LOSH/issues/36#issuecomment-738812791) in #36)

Sorry, couldn't grasp your point here.

What would be a benefit of (re-)creating this property? We won't use `name` for referencing reasons.
