### ISSUE TITLE
[osh-metadata.ttl wikibase review] QU: Component language? (okh:language)

### ISSUE THREAD

**Issue by addshore** [OPEN-NEXT/LOSH#39]
https://github.com/OPEN-NEXT/LOSH/blob/master/osh-metadata.ttl#L190-L197

Components have a language?
Perhaps the term "language" here just needs to be specified further?
I don't see how a physical thing can have a language?
Perhaps this refers to something about the component such as the design detail docs etc or something else linked form the compoennt?

**Comment by moedn** [comment]
Yes, this refers to the language a certain piece of documentation is written in. After all, the only thing we can upload on development platforms is the documentation of components. Even technical drawings often contain descriptions, specifications and instructions. But (usually) languages are not mixed in the same documents which means we can also have unambiguous references to those e.g. for packaging reasons (=a download button for the Japanese version of project [crkbd](https://github.com/foostan/crkbd))

So `okh:language` refers to the language the _documentation_ of a component is written in. This of course 
- only applies for `module` and `piece` → so we should redefine `domain`,
- should be noted in a `comment` to avoid confusion

**Comment by hoijui** [comment]
@addshore Is it now ok? (see commit linked to above)

**Comment by addshore** [comment]
To me `rdfs:label "language" ;` still feels unclear.

Personally I think calling it what it is would be clearer, so "Documentation language" or "Primary documentation language"
However the comment change in https://github.com/OPEN-NEXT/LOSH/commit/db2ba4b0a334a66cb6d184697ad37287ef162356 is already a good change.

**Comment by moedn** [comment]
has been renamed to `documentationLanguage`
