### ISSUE TITLE
Mechanism for API authentication w/ Wikibase/crawler?

### ISSUE THREAD

**Issue by penyuan** [OPEN-NEXT/LOSH#41]
In our recent meetings, we talked about the option of moving data between the WP2.2 dashboard and the WP3.3 Wikibase instance/crawler via its API.

Will there be authentication required for API access for read and write? If so, what is its mechanism? Tokens, keys, username/password?

**Comment by hoijui** [comment]
what is WP2.2 and WP3.3?

**Comment by penyuan** [comment]
> what is WP2.2 and WP3.3?

Oh sorry. They are parts of the Open!Next project to which this repository belongs. WP stands for "work package."

I am responsible for WP2.2 which is for creating an online-accessible dashboard that shows metrics for open source hardware projects hosted on version control platforms such as GitHub, Wikifactory, and I hope others like GitLab. I've talked to @moedn about integrating WP2.2 with the Wikibase instance and the crawler.

For example, the dashboard is supposed to have a data-mining script that pulls data from those repositories to show. One way to do this is to integrate this functionality into a module of the crawler. This data can be stored in the Wikibase instance for the dashboard to access.

To allow such access, presumably the Wikibase instance will have a data access API. So my question was asking how this API will be design, what the interface will look like and if authentication is required.

**Comment by moedn** [comment]
I assume this question goes to @addshore  :)

**Comment by addshore** [comment]
Either a user login method can be used https://www.mediawiki.org/wiki/API:Login
Or OAuth can be used https://www.mediawiki.org/wiki/OAuth

**Comment by moedn** [comment]
@penyuan does this answer your question?

**Comment by penyuan** [comment]
Sorry for late response. The above sounds fine to me. I'll just need to know what API endpoint(s) (if any?) to interface with once they're ready. Thanks!

**Comment by moedn** [comment]
@penyuan further questions are better allocated [in this repo](https://github.com/wmde/WikibaseReconcileEdit) :)
