### ISSUE TITLE
[osh-metadata.ttl wikibase review] Use of multiple rdfs:comment

### ISSUE THREAD

**Issue by addshore** [OPEN-NEXT/LOSH#47]
Multiple `rdfs:comment` are used in at least one place.
I first noticed this in https://github.com/OPEN-NEXT/LOSH/commit/db2ba4b0a334a66cb6d184697ad37287ef162356#diff-1dac5e59384cbca06417a712bc81907249e40b96f004478b3f583d5455c37068R173-R175

I don't believe `rdfs:comment` will end up in the Wikibase RDF output at all.

These comments probably want to map to either a Wikibase entity description, or to a statement on an entity.
If this is a description, then a single entity can only have a single description in a language.

So in the example attached I could imagine this being "IETF language tag denoting the language of the documentation following the BCP 47 standard e.g. en-GB"

**Comment by moedn** [comment]
should be resolved; feel free to re-open this issue otherwise :)
