### ISSUE TITLE
Should the BoM be parsed into RDF as well? (and back?)

### ISSUE THREAD

**Issue by hoijui** [OPEN-NEXT/LOSH#48]
... kind of makes sense, and it could even potentially be parsed from JSON, alternatively, instead of CSV.

**Comment by moedn** [comment]
BoM should be parsed into JSON / JSON-LD so it can be submitted to the Wikibase-API.

CSV should remain as file format since most engineering software will export the BoM as CSV or any table-based format

**Comment by moedn** [comment]
update: yes (but not back) :)
