### ISSUE TITLE
upload all pictures to Wikimedia Commons

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#59]
since Wikibase doesn't support images outside Wikimedia Commons (alternative: local pictures + dead links), we'd need to upload them all there (= a job for the crawler)

**Comment by moedn** [comment]
OR we use Wikibase just as a backend + UI, with no visualisation at all (which is anyway an issue with Wikibase)

**Comment by lucaswerkmeister** [comment]
Or: [Wikibase Local Media](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:Wikibase_Local_Media)

**Comment by penyuan** [comment]
Quick thought: One advantage of uploading images to Wikimedia Commons is that it is (1) a long term and reliable archive and (2) reduces the administrative and maintainence burden for us.

**Comment by moedn** [comment]
Update: in the last meeting we clarified that content will only be linked and displayed, not stored on our side. This includes images. Hence, metadata will link to images and the frontend will try to display them. So all data remains upstream :)
