### ISSUE TITLE
Related work: CodeMeta

### ISSUE THREAD

**Issue by cyroxx** [OPEN-NEXT/LOSH#71]
A similar idea like this project, although probably a bit more focused on software: https://codemeta.github.io/

**Comment by moedn** [comment]
Thanks, indeed super interesting! It seems rather dead (or at least not very active), but idea and approach are very good. The specific challenge/benefit we have with hardware is that there are no widespread metadata concepts existent yet that we could compare and build on.
There's

- open know-how (as linked in the README)
- individual API data from various platforms (as OSHWA certification list etc.)

So our approach is to improve the open know-how specification and map the data available via APIs of various OSH platforms onto it.

Anyway, I'll definitely mention this project in the report for the EU :)
