### ISSUE TITLE
new concept removing sBoM.csv

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH#74]
The sBoM concept brings several disadvantages while advantages are not prevailing at the moment, plus it's not technically necessary anymore.

**Disadvantages:**

- building the sBoM takes a significant effort in the metadata creation (← manual work)
- the sBoM template is not standardised outside this repository
- the sBoM structure lacks some functions due to its simplistic approach (e.g. various columns for specific part referencing (e.g. electronic components) as suggested in #16) and has some ambiguity in it (e.g. position number & unit count for subassemblies in the sBoM ← indeed an issue that is still open even in official BoM standards)

**Advantages:**

- BUY and STD parts become accessible to the graph database and can hence be analysed & combined with other data (what we don't do at the moment)
- simple overview of all parts directly visible for the user when searching MOSHes; specifically useful when comparing MOSHes

---

There are dozens of standards for BoMs and I'm not seeing the benefit anymore of exposing a new, not well-tested approach to world. To follow our metadata specification, people are forced to either adopt to the sBoM template in regards of their own BoM or to produce redundant information in case they already have a BoM.

---

**Suggested solution:**

The important part is that all relevant information is accessible. 

- This can be done in MOSH & POSH files.
- A MOSH file contains then 
  - URL to the BoM
  - URLs to POSH files
  - URLs to MOSH releases/snapshots 
  - rest remains unchanged
- POSH files remain unchanged

Open question: When MOSHes that follow this metadata specifications are referring to each other (MOSH A v1.0 uses MOSH B v1.2) → is version-specific linking possible just based on the given URL which may be either a release or a commit?\
I assume yes, but it would require some extra effort (= system can be upgraded later)\
If we could only link to the versionless MOSH (was called TOSH in some issue), this would already be from great value. Which specific version was used or which specific BUY parts are in there are all relevant and good, but not crucial questions. We still don't know if people actually need this detailed level of information in a graph database. And if it turns out that they need it → this would be a great outcome of a research project and we can upgrade the system for a reason.

Next step (after OPEN!NEXT, I presume) would be to standardise BoMs for OSH (and likewise other reoccurring parts of the documentation like README). And _this_ seems like a bigger issue and may even turn out to be unsolvable at the moment as this stuff seems to be technology- and even target-group-specific.

**Comment by julianstirling** [comment]
My thoughts on this are somewhat related to my own biases and my own work. I also don't have and in depth understanding of the MOSH POSH file structure. But here goes:

* There will never be a CSV file that captures all BOMs. BOMS are hierarchical and must extensible for new circumstances. I would choose a format like JSON, YAML, TOML, even maybe XML (except I hate XML). This way you can create an extensible schema.
* You can have technology specific CSVs which can be shaped into the more general hierarchical schema for people that like CSVs that sit in an easy an well defined area.
* Requiring too much information at the outset in a barrier to entry. If a CSV of `name, qty, link` can work, but give you a low "completeness" score, they you get people online and you have a carrot for them to work their way up the search results.
* From a [GitBuilding](https://gitbuilding.io) perspective this allows me to generate a BOM on the fly and put as much meta data as I have into the correct from for the crawler. It would be important in this case to not require that the BOM is in the repository, as it would be generated automatically and would available on a generated webpage.

---
 As an example of why the schema should be hierarchical is that for a white LED it is pretty important that I can specify things like:
 * Viewing angle
 * Colour temperature
 * Current rating
 * Package type

Capturing this in the BOM so it can be compared to other components to assess local availability would be great. Some of these apply well to other electronic components, others less well. None of them make much sense if I am speccing a wing nut.

**Comment by hoijui** [comment]
+1 on allowing the (s)BOM to reside in an other place (generated).

My first impulse is, to keep the current approach of sBOM.csv (in a flexible location) for the demonstrator,
but keep that part of the crawler modular, so it would be easy to support multiple formats.
The key idea behind this, is that the real BOM is the resulting RDF, and how we get to it, is secondary.

I imagine a scheme, where wikifactory for example, have their BOM data in a totally different format (e.g. an SQL database), and are able to offer it through an API specific to them, including a conversion script to generate RDF from it, that the crawler could call for each project.

I also like the idea of different levels of completeness of the BOM (only MOSHes and POSHes, or also BUY and STD parts), which will lead to different completeness scores.
I woudl liek to have all that data for at least some of our example projects, though.

**Comment by moedn** [comment]
Alright, so from this perspective it perfectly makes sense to

1. link to the human-readable form of the BoM (regardless of its structure or file format)
2. keep some kind of interface to get BoM data (yet wikifactory does not capture this so there's no way to pull this information from their API at the moment – however this may change in the future since it's valuable information to have)
3. remove the `sBoM.csv` approach since we won't use this template in the future anyway
4. provide complete BoM data for our example projects. I think the specific format can be chosen in a quick chat between @ahane @hoijui and me (e.g. could be just additional fields in the TOML)

Thanks for your input! Things make a lot more sense now :)
